require 'nanoc2/base/proxies/asset_proxy'
require 'nanoc2/base/proxies/asset_rep_proxy'
require 'nanoc2/base/proxies/layout_proxy'
require 'nanoc2/base/proxies/page_proxy'
require 'nanoc2/base/proxies/page_rep_proxy'
